### ISSUE TITLE
ShapeEditor: undo operation

### ISSUE THREAD

**Issue by robertosalemi** [ViceIce/DotSpatial#3]
Hi,
thanks for plugin ShapeEditor.
It is possible implement a function for the "undo operation" of the modify executed by user?

Thanks!

**Comment by ViceIce** [comment]
Hi @robertosalemi ,

this repository is only a mirror of http://dotspatial.codeplex.com. So please ask there for assistance.

Regards,
Michael

**Comment by robertosalemi** [comment]
Thanks! :)
